//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stellar.Pluralize.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stellar.Pluralize.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to person,people,persons
        ///schema,schemata,schemas
        ///child,children,childs
        ///foot,feet,foots
        ///tooth,teeth,tooths
        ///mouse,mice,mouses
        ///cactus,cacti,cactuses
        ///focus,foci,focuses
        ///nucleus,nuclei,nucleuses
        ///fungus,fungi,funguses
        ///radius,radii,radiuses
        ///.
        /// </summary>
        internal static string Irregulars {
            get {
                return ResourceManager.GetString("Irregulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dingo,dingos
        ///mango,mangoes
        ///echo,echos
        ///ghetto,ghettoes
        ///nucleus,nucleuses
        ///bureau,bureaux
        ///seraph,seraphs
        ///species,species.
        /// </summary>
        internal static string Plurals {
            get {
                return ResourceManager.GetString("Plurals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whisky,whiskies
        ///plateaux,plateaux
        ///basis,bases
        ///axis,axes
        ///automatum,automata
        ///thou,you
        ///passerby,passersby
        ///species,species.
        /// </summary>
        internal static string Singulars {
            get {
                return ResourceManager.GetString("Singulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firmware,firmware
        ///fish,fish
        ///media,media
        ///moose,moose
        ///police,police
        ///sheep,sheep
        ///series,series
        ///species,species
        ///agenda,agenda
        ///news,news
        ///reindeer,reindeer
        ///starfish,starfish
        ///smallpox,smallpox
        ///tennis,tennis
        ///chickenpox,chickenpox
        ///shambles,shambles
        ///garbage,garbage
        ///you,you
        ///wildlife,wildlife
        ///Staff,Staff
        ///STAFF,STAFF
        ///turquois,turquois
        ///turquoise,turquoises
        ///carnivorous,carnivorous
        ///only,only
        ///aircraft,aircraft
        ///veniam,veniam
        ///this,these
        ///that,those
        ///is,are
        ///man,men
        ///superman,supermen
        ///ox,oxen
        ///bus,b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
    }
}
